#!/bin/sh

switch_mode() {
    case $1 in 
        -SOURCE)
            echo "0source"
            ;;
        -COMMANDS)
            echo "0commands"
            ;;
        -LIBS)
            echo "0libs"
            ;;
        *)
            echo "1$1"
    esac
}

MODE="source"
ARGS=""
if [ -e cxxproj ]; then
    while read p; do
    R="$(switch_mode $p)"
    RESL=$(echo "$R" | cut -c1)
    if [ "$RESL" = "0" ]; then
        MODE=$(echo "$R" | cut -c2-)
    else
        case $MODE in
            "libs")
                ARGS="$ARGS -l$p"
                ;;
            "source")
                ARGS="$ARGS $p"
                ;;
            "commands")
                ARGS="$ARGS `$p`"
                ;;
        esac
    fi
    done <cxxproj
fi


echo "gcc $@ $ARGS && ./a.out"
gcc $@ $ARGS && ./a.out

